package com.example.demo.domain;

import jakarta.persistence.*;
import lombok.Getter;
import lombok.Setter;
import lombok.ToString;

import java.util.List;
import java.util.Objects;

@Getter
@Setter
@ToString
@Entity
public class Perfume {
    @Id
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "perfume_id_seq")
    @SequenceGenerator(name = "perfume_id_seq", sequenceName = "perfume_id_seq", initialValue = 109, allocationSize = 1)
    private Long id;

    private String perfumeTitle;

    private String perfumer;

    private Integer year;

    private String country;

    private String perfumeGender;

    private String fragranceTopNotes;

    private String fragranceMiddleNotes;

    private String fragranceBaseNotes;

    private String description;

    private String filename;

    private Integer price;

    private String volume;

    private String type;

    private Double perfumeRating;

    @OneToMany
    @ToString.Exclude
    private List<Review> reviews;

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        Perfume perfume = (Perfume) o;
        return Objects.equals(id, perfume.id);
    }

    @Override
    public int hashCode() {
        return Objects.hash(id);
    }
}


// @ToString.Exclude is used to exclude a specific field from being included in the toString() method generated by Lombok.